import { css } from '~/styled-system/css'

export const searchUiStyles = {
  page: css({
    minH: 'screen',
    bg: 'gray.50',
    py: { base: '10', md: '16' },
    px: { base: '4', md: '8' },
  }),
  layout: css({
    maxW: '6xl',
    mx: 'auto',
    display: 'grid',
    gap: { base: '8', lg: '10' },
  }),
  searchCard: css({
    bg: 'white',
    borderRadius: '2xl',
    border: '1px solid',
    borderColor: 'gray.100',
    shadow: 'lg',
    p: { base: '6', md: '8' },
    display: 'flex',
    flexDirection: 'column',
    gap: '6',
  }),
  resultsCard: css({
    bg: 'white',
    borderRadius: '2xl',
    border: '1px solid',
    borderColor: 'gray.100',
    shadow: 'lg',
    p: { base: '6', md: '8' },
  }),
  accentLabel: css({
    fontSize: 'sm',
    fontWeight: 'semibold',
    color: 'purple.600',
    letterSpacing: 'widest',
    textTransform: 'uppercase',
  }),
  heading: css({
    fontSize: { base: '2xl', md: '3xl' },
    fontWeight: 'bold',
    color: 'gray.900',
  }),
  description: css({
    color: 'gray.600',
    lineHeight: 'tall',
  }),
  filtersStack: css({
    display: 'flex',
    flexDirection: 'column',
    gap: '5',
  }),
  inputLabel: css({
    display: 'block',
    fontSize: 'sm',
    fontWeight: 'semibold',
    color: 'gray.700',
    mb: '2',
  }),
  helperText: css({
    fontSize: 'sm',
    color: 'gray.500',
    mt: '1',
  }),
  queryInput: css({
    width: '100%',
    borderRadius: 'xl',
    border: '1px solid',
    borderColor: 'gray.200',
    px: '4',
    py: '3',
    fontSize: 'md',
    transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    _focus: {
      borderColor: 'purple.500',
      boxShadow: '0 0 0 3px rgba(168, 85, 247, 0.25)',
      outline: 'none',
    },
  }),
  tagList: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: '2',
  }),
  tagButton: css({
    borderRadius: 'full',
    border: '1px solid',
    borderColor: 'gray.200',
    px: '4',
    py: '2',
    fontSize: 'sm',
    color: 'gray.700',
    bg: 'white',
    transition: 'all 0.2s ease',
    cursor: 'pointer',
    _hover: {
      borderColor: 'purple.300',
      color: 'purple.600',
    },
  }),
  tagButtonActive: css({
    bg: 'purple.600',
    color: 'white',
    borderColor: 'purple.600',
    boxShadow: '0 8px 20px rgba(139, 92, 246, 0.45)',
  }),
  select: css({
    width: '100%',
    borderRadius: 'xl',
    border: '1px solid',
    borderColor: 'gray.200',
    px: '4',
    py: '3',
    fontSize: 'md',
    bg: 'white',
  }),
  statsBar: css({
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: { base: 'column', md: 'row' },
    gap: '4',
    mb: '6',
  }),
  statsTitle: css({
    fontSize: 'xl',
    fontWeight: 'semibold',
    color: 'gray.900',
  }),
  statsSubtitle: css({
    fontSize: 'sm',
    color: 'gray.600',
  }),
  methodBadge: css({
    alignSelf: 'flex-start',
    borderRadius: 'full',
    background: 'purple.50',
    color: 'purple.700',
    fontSize: 'sm',
    fontWeight: 'semibold',
    px: '4',
    py: '2',
  }),
  activeFilters: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: '2',
    alignItems: 'center',
    mb: '4',
  }),
  activeChip: css({
    borderRadius: 'full',
    background: 'gray.100',
    color: 'gray.700',
    fontSize: 'sm',
    px: '3',
    py: '1',
  }),
  resetButton: css({
    border: 'none',
    background: 'transparent',
    color: 'purple.600',
    fontWeight: 'semibold',
    cursor: 'pointer',
    textDecoration: 'underline',
  }),
  resultList: css({
    listStyleType: 'none',
    display: 'grid',
    gap: '4',
    margin: 0,
    padding: 0,
  }),
  resultCard: css({
    borderRadius: 'xl',
    border: '1px solid',
    borderColor: 'gray.100',
    padding: '5',
    background: 'gray.50',
    display: 'flex',
    flexDirection: 'column',
    gap: '3',
  }),
  cardHeader: css({
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: { base: 'column', md: 'row' },
    gap: '3',
  }),
  cardTitle: css({
    fontSize: 'lg',
    fontWeight: 'semibold',
    color: 'gray.900',
  }),
  cardMeta: css({
    fontSize: 'sm',
    color: 'gray.600',
  }),
  difficultyBadge: css({
    alignSelf: 'flex-start',
    borderRadius: 'full',
    background: 'gray.900',
    color: 'white',
    fontSize: 'xs',
    fontWeight: 'semibold',
    px: '3',
    py: '1',
    textTransform: 'uppercase',
    letterSpacing: 'widest',
  }),
  cardDescription: css({
    color: 'gray.700',
    lineHeight: 'tall',
  }),
  cardFooter: css({
    display: 'flex',
    flexDirection: { base: 'column', md: 'row' },
    gap: '3',
    justifyContent: 'space-between',
  }),
  metrics: css({
    display: 'flex',
    flexWrap: 'wrap',
    gap: '3',
    fontSize: 'sm',
    color: 'gray.600',
  }),
  resultTag: css({
    borderRadius: 'full',
    background: 'white',
    border: '1px solid',
    borderColor: 'gray.200',
    fontSize: 'xs',
    color: 'gray.600',
    px: '3',
    py: '1',
  }),
  emptyState: css({
    textAlign: 'center',
    padding: '10',
    color: 'gray.500',
    borderRadius: 'xl',
    border: '1px dashed',
    borderColor: 'gray.200',
    background: 'gray.50',
  }),
}
